version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    entrypoint: cat
    command: ""
    tty: true
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}