# Generated by Django 3.2.23 on 2023-11-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='score',
            field=models.FloatField(blank=True, db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='score_description',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
