# Generated by Django 3.2.23 on 2023-11-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='domain_zones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highlights',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='looking_for',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='moreinfo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='secondary_keyword',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills_cache',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='uninterested_company_types',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='country',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='extra_keywords',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='long_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='primary_keyword',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='secondary_keyword',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='feedback_candidate',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='feedback_recruiter',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
