# Generated by Django 4.2.7 on 2023-11-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
