# Generated by Django 3.2.23 on 2023-11-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0002_auto_20231108_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="english_level_weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="exp_years_weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="location_weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="primary_keyword_weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="salary_weight",
            field=models.FloatField(default=1.0),
        ),
    ]
